site_name: Joel's Resource Landing Page

theme:
  name: material
  logo: assets/globe.png
  features:
    - header.autohide
  palette:
    scheme: slate

nav:
  - Landing Page: index.md
  - Situational Reports:
    - sitreps/index.md

plugins:
  - search
  - blog:
      blog_dir: sitreps
      post_date_format: dd MMM YYYY
      archive_date_format: yyyy MMM
