site_name: Joel's Resource Page

theme:
  name: material
  logo: assets/esri-17GlobeLogo_tag-right_1CRev.png
  palette:
    scheme: slate
    primary: black
  features:
    - content.code.copy

nav:
  - Landing Page: index.md
  - Situational Reports:
    - sitreps/index.md

plugins:
  - search
  - blog:
      blog_dir: sitreps
      post_date_format: dd MMM YYYY
      archive_date_format: MMM yyyy
      archive_url_date_format: yyyy/MM
