site_name: Joel's Resource Page

theme:
  name: material
  logo: assets/esri-17GlobeLogo_tag-right_1CRev.png
  palette:
    scheme: slate
    primary: black
  features:
    - content.code.copy

nav:
  - Landing Page: index.md
  - Situational Reports:
    - sitreps/index.md
  - GeoAnalytics:
    - GeoAnalytics Notes: geoanalytics.md
    - Overlay with H3 and GeoAnalytics: notebooks/0.20-intersect-h3-geoanalytics.ipynb
  - Add H3 to ArcGIS Pro: add_h3_pro.md
  - Azure Function Development on Mac: azure_function_setup.md
  - Switching ArcGIS Feature Service View Source: arcgis_swap_view_source.md

plugins:
  - search
  - blog:
      blog_dir: sitreps
      post_date_format: dd MMM YYYY
      archive_date_format: MMM yyyy
      archive_url_date_format: yyyy/MM

  # extension converting included notebooks into html at build time
  - mkdocs-jupyter:
      include_source: true

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      linenums: true
      anchor_linenums: true
  - pymdownx.superfences
